<Project>
  <Sdk Name="Microsoft.NET.Sdk" />
  <Sdk Name="ktsu.Sdk" />

  <PropertyGroup>
    <TargetFrameworks>net10.0;net9.0;net8.0</TargetFrameworks>
    <RootNamespace>ktsu.ImGui.Probes</RootNamespace>
    <AssemblyName>$(RootNamespace)</AssemblyName>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Hexa.NET.ImGui" />
    <PackageReference Include="Polyfill" PrivateAssets="all" />
  </ItemGroup>

</Project>
