// Copyright (c) ktsu.dev
// All rights reserved.
// Licensed under the MIT license.

namespace ktsu.ForceDirectedLayout;

using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

/// <summary>
/// Error codes returned by every <see cref="NativeExports"/> entry point.
/// Negative values indicate failure. The C header generated by the AOT compiler exposes these as constants.
/// </summary>
public static class LayoutResult
{
	/// <summary>Operation succeeded.</summary>
	public const int Ok = 0;

	/// <summary>The provided handle was null or has already been destroyed.</summary>
	public const int InvalidHandle = -1;

	/// <summary>A required pointer argument was null.</summary>
	public const int NullArgument = -2;

	/// <summary>An integer or buffer length was out of range (e.g. negative, or destination too small).</summary>
	public const int OutOfRange = -3;

	/// <summary>An unhandled managed exception was caught at the boundary. Inspect last-error for details.</summary>
	public const int InternalError = -4;

	/// <summary>The requested node index does not refer to a known body.</summary>
	public const int UnknownNode = -5;
}

/// <summary>
/// C ABI surface for <see cref="ForceLayout"/>. All entries are <c>[UnmanagedCallersOnly]</c> with sequential POD signatures
/// and return <see cref="LayoutResult"/> integers. Exceptions are converted to error codes at the boundary - none escape.
/// </summary>
/// <remarks>
/// Handles are opaque to native callers and represent an allocated <see cref="GCHandle"/> wrapping a managed <see cref="ForceLayout"/>.
/// Every Create must be paired with a Destroy; failure to do so leaks the managed instance and pins it against GC.
///
/// All buffer parameters are caller-owned. The library writes into the buffer but never retains a pointer past the call return.
/// </remarks>
public static unsafe class NativeExports
{
	[ThreadStatic]
	private static string? lastError;

	/// <summary>Create a new layout context with the given configuration. Returns a non-null handle on success.</summary>
	[UnmanagedCallersOnly(EntryPoint = "Layout_Create")]
	public static IntPtr Create(LayoutSettings* config)
	{
		try
		{
			ForceLayout instance = new();
			if (config != null)
			{
				instance.Settings = *config;
			}
			GCHandle handle = GCHandle.Alloc(instance);
			return GCHandle.ToIntPtr(handle);
		}
		catch (Exception ex)
		{
			lastError = ex.ToString();
			return IntPtr.Zero;
		}
	}

	/// <summary>Destroy a layout context. After this call the handle is invalid.</summary>
	[UnmanagedCallersOnly(EntryPoint = "Layout_Destroy")]
	public static int Destroy(IntPtr handle)
	{
		try
		{
			if (!TryResolve(handle, out _, out GCHandle gch))
			{
				return LayoutResult.InvalidHandle;
			}
			gch.Free();
			return LayoutResult.Ok;
		}
		catch (Exception ex)
		{
			lastError = ex.ToString();
			return LayoutResult.InternalError;
		}
	}

	/// <summary>Update the simulation settings on an existing context.</summary>
	[UnmanagedCallersOnly(EntryPoint = "Layout_SetSettings")]
	public static int SetSettings(IntPtr handle, LayoutSettings* config)
	{
		try
		{
			if (!TryResolve(handle, out ForceLayout layout, out _))
			{
				return LayoutResult.InvalidHandle;
			}
			if (config == null)
			{
				return LayoutResult.NullArgument;
			}
			layout.Settings = *config;
			return LayoutResult.Ok;
		}
		catch (Exception ex)
		{
			lastError = ex.ToString();
			return LayoutResult.InternalError;
		}
	}

	/// <summary>Replace the body set. <paramref name="nodes"/> is a pointer to <paramref name="count"/> contiguous <see cref="NodeInit"/> entries.</summary>
	[UnmanagedCallersOnly(EntryPoint = "Layout_SetNodes")]
	public static int SetNodes(IntPtr handle, NodeInit* nodes, int count)
	{
		try
		{
			if (!TryResolve(handle, out ForceLayout layout, out _))
			{
				return LayoutResult.InvalidHandle;
			}
			if (count < 0)
			{
				return LayoutResult.OutOfRange;
			}
			if (count > 0 && nodes == null)
			{
				return LayoutResult.NullArgument;
			}
			ReadOnlySpan<NodeInit> span = count == 0 ? [] : new ReadOnlySpan<NodeInit>(nodes, count);
			layout.SetNodes(span);
			return LayoutResult.Ok;
		}
		catch (Exception ex)
		{
			lastError = ex.ToString();
			return LayoutResult.InternalError;
		}
	}

	/// <summary>Replace the edge set. Endpoint ids must match previously submitted nodes.</summary>
	[UnmanagedCallersOnly(EntryPoint = "Layout_SetEdges")]
	public static int SetEdges(IntPtr handle, EdgeInit* edges, int count)
	{
		try
		{
			if (!TryResolve(handle, out ForceLayout layout, out _))
			{
				return LayoutResult.InvalidHandle;
			}
			if (count < 0)
			{
				return LayoutResult.OutOfRange;
			}
			if (count > 0 && edges == null)
			{
				return LayoutResult.NullArgument;
			}
			ReadOnlySpan<EdgeInit> span = count == 0 ? [] : new ReadOnlySpan<EdgeInit>(edges, count);
			layout.SetEdges(span);
			return LayoutResult.Ok;
		}
		catch (Exception ex)
		{
			lastError = ex.ToString();
			return LayoutResult.InternalError;
		}
	}

	/// <summary>Advance the simulation by <paramref name="dt"/> seconds.</summary>
	[UnmanagedCallersOnly(EntryPoint = "Layout_Step")]
	public static int Step(IntPtr handle, double dt)
	{
		try
		{
			if (!TryResolve(handle, out ForceLayout layout, out _))
			{
				return LayoutResult.InvalidHandle;
			}
			layout.Step(dt);
			return LayoutResult.Ok;
		}
		catch (Exception ex)
		{
			lastError = ex.ToString();
			return LayoutResult.InternalError;
		}
	}

	/// <summary>Solve to convergence or until <paramref name="maxIterations"/> ticks are exhausted.</summary>
	[UnmanagedCallersOnly(EntryPoint = "Layout_Solve")]
	public static int Solve(IntPtr handle, int maxIterations, double tolerance)
	{
		try
		{
			if (!TryResolve(handle, out ForceLayout layout, out _))
			{
				return LayoutResult.InvalidHandle;
			}
			if (maxIterations < 0)
			{
				return LayoutResult.OutOfRange;
			}
			layout.Solve(maxIterations, tolerance);
			return LayoutResult.Ok;
		}
		catch (Exception ex)
		{
			lastError = ex.ToString();
			return LayoutResult.InternalError;
		}
	}

	/// <summary>Read current positions into a caller-owned buffer of <paramref name="bufferLen"/> entries.</summary>
	[UnmanagedCallersOnly(EntryPoint = "Layout_GetPositions")]
	public static int GetPositions(IntPtr handle, NodePosition* outBuffer, int bufferLen)
	{
		try
		{
			if (!TryResolve(handle, out ForceLayout layout, out _))
			{
				return LayoutResult.InvalidHandle;
			}
			if (layout.NodeCount == 0)
			{
				return 0;
			}
			if (bufferLen < layout.NodeCount)
			{
				return LayoutResult.OutOfRange;
			}
			if (outBuffer == null)
			{
				return LayoutResult.NullArgument;
			}
			Span<NodePosition> span = new(outBuffer, bufferLen);
			return layout.GetPositions(span);
		}
		catch (Exception ex)
		{
			lastError = ex.ToString();
			return LayoutResult.InternalError;
		}
	}

	/// <summary>Pin or unpin a body by working-buffer index. Use <see cref="GetIndexOf"/> to resolve an id to an index.</summary>
	[UnmanagedCallersOnly(EntryPoint = "Layout_SetPinned")]
	public static int SetPinned(IntPtr handle, int nodeIndex, byte pinned)
	{
		try
		{
			if (!TryResolve(handle, out ForceLayout layout, out _))
			{
				return LayoutResult.InvalidHandle;
			}
			if ((uint)nodeIndex >= (uint)layout.NodeCount)
			{
				return LayoutResult.UnknownNode;
			}
			layout.SetPinned(nodeIndex, pinned != 0);
			return LayoutResult.Ok;
		}
		catch (Exception ex)
		{
			lastError = ex.ToString();
			return LayoutResult.InternalError;
		}
	}

	/// <summary>Resolve a caller-assigned node id to its working-buffer index. Writes -1 if unknown.</summary>
	[UnmanagedCallersOnly(EntryPoint = "Layout_GetIndexOf")]
	public static int GetIndexOf(IntPtr handle, int nodeId, int* outIndex)
	{
		try
		{
			if (!TryResolve(handle, out ForceLayout layout, out _))
			{
				return LayoutResult.InvalidHandle;
			}
			if (outIndex == null)
			{
				return LayoutResult.NullArgument;
			}
			*outIndex = layout.GetIndexOf(nodeId);
			return LayoutResult.Ok;
		}
		catch (Exception ex)
		{
			lastError = ex.ToString();
			return LayoutResult.InternalError;
		}
	}

	/// <summary>Query the current node count.</summary>
	[UnmanagedCallersOnly(EntryPoint = "Layout_GetNodeCount")]
	public static int GetNodeCount(IntPtr handle, int* outCount)
	{
		try
		{
			if (!TryResolve(handle, out ForceLayout layout, out _))
			{
				return LayoutResult.InvalidHandle;
			}
			if (outCount == null)
			{
				return LayoutResult.NullArgument;
			}
			*outCount = layout.NodeCount;
			return LayoutResult.Ok;
		}
		catch (Exception ex)
		{
			lastError = ex.ToString();
			return LayoutResult.InternalError;
		}
	}

	/// <summary>
	/// Return the UTF-8 byte length of the last error message captured on this thread, and (if non-null)
	/// copy up to <paramref name="bufferLen"/> bytes into <paramref name="outBuffer"/>. The string is NOT null-terminated.
	/// Returns negative <see cref="LayoutResult"/> on argument errors, otherwise the byte length (possibly 0).
	/// </summary>
	[UnmanagedCallersOnly(EntryPoint = "Layout_GetLastErrorMessage")]
	public static int GetLastErrorMessage(byte* outBuffer, int bufferLen)
	{
		try
		{
			string err = lastError ?? string.Empty;
			int byteLen = System.Text.Encoding.UTF8.GetByteCount(err);
			if (outBuffer != null && bufferLen > 0)
			{
				Span<byte> dst = new(outBuffer, Math.Min(bufferLen, byteLen));
				System.Text.Encoding.UTF8.GetBytes(err, dst);
			}
			return byteLen;
		}
		catch
		{
			return LayoutResult.InternalError;
		}
	}

	[MethodImpl(MethodImplOptions.AggressiveInlining)]
	private static bool TryResolve(IntPtr handle, out ForceLayout layout, out GCHandle gch)
	{
		if (handle == IntPtr.Zero)
		{
			layout = null!;
			gch = default;
			return false;
		}

		gch = GCHandle.FromIntPtr(handle);
		if (!gch.IsAllocated || gch.Target is not ForceLayout l)
		{
			layout = null!;
			return false;
		}
		layout = l;
		return true;
	}
}
